
dcsa:
  specification:
    version: 1.1.0
  webui:
    baseUrl: "NOT_SPECIFIED"
  email:
    from: noreply@dcsa.org
    timezone: "NOT_SPECIFIED"
    dateFormat: MM/LLL/yyyy HH:mm
    templates:
      timestampReceived:
        onlyForEventClassifierCode:
          - EST
          - REQ
        subject: Response requested on timestamp from vessel {{VESSEL_NAME}}.
        body: |
          <p>Vessel {{VESSEL_NAME}} // IMO{{VESSEL_IMO_NUMBER}} registered a new {{TIMESTAMP_TYPE}}. Your response is required.</p>
          <p>Please go to <a href="{{WEB_UI_BASE_URI}}/transportcall/{{PORT_VISIT_ID}}">{{WEB_UI_BASE_URI}}/transportcall/{{PORT_VISIT_ID}}</a> and respond to the timestamp.</p>

camel:
  max-redeliveries: 3
  redelivery-delay: 10000
  route:
    pending-email-notification: "jpa:org.dcsa.jit.persistence.entity.PendingEmailNotification?namedQuery=PendingEmailNotification.nextPendingEmailNotifications&delay=60000&maximumResults=10"

spring:
  application:
    name: DCSA-JIT
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}/dcsa_openapi
    username: dcsa_db_owner
    hikari:
      schema: dcsa_im_v3_0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  profiles:
    active: nosecurity
    group:
      dev: nosecurity, logsql, localdb, fakesmtpserver
      test: nosecurity, logsql, localdb, fakesmtpserver
      prod: default
  mail:
    # Syntactically correct host name that will fail to resolve
    # in DNS.  The hostname should be guide most admins to the
    # proper solution. :)
    host: please-set-spring.mail.host-property-in-dcsa-app.invalid
    # Leave username and password undefined here.
    # That should be a deployment specific option
    #
    # See https://www.baeldung.com/spring-email for some
    # examples.
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          # Leave port and auth undefined here.
          # That should be a deployment specific option
          starttls:
            # We use a strict default.
            enable: true
            required: true

server:
  port: 9090
  servlet.context-path: /v1
  error:
    include-binding-errors: on_param
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:INFO}
      dcsa: ${DCSA_LOG_LEVEL:INFO}

---
# A profile for disabling security
spring:
  config:
    activate:
      on-profile: nosecurity

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

---
# A profile for connecting to a local database
spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname:localhost}/dcsa_openapi
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5

---
# A profile to disable the mail check component of actuator (or health checks fails in dev and test)
spring:
  config:
    activate:
      on-profile: fakesmtpserver

management:
  health:
    mail:
      enabled: false

---
# A profile for logging the sql generated by jpa
spring:
  config:
    activate:
      on-profile: logsql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
