name: Publish RELEASE

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: github
          server-username: ${{ secrets.DCSA_USER }}
          server-password: ${{ secrets.DCSA_PACKAGES_PAT }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Core", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "github", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'    

      - name: Publish package
        run: mvn -B deploy -Dchangelist=-RELEASE
